version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '1234:80'
    volumes:
      - ./app/src:/var/www/html

  db:
    image: 'mariadb'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: data
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '3306:80'
    environment:
      - PMA_ARBITRARY=1