CREATE TABLE IF NOT EXISTS User (
  id INT AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  admin BOOLEAN NOT NULL,
  PRIMARY KEY (id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Post (
  id INT AUTO_INCREMENT,
  user INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content VARCHAR(255) NOT NULL,
  date DATETIME NOT NULL,
  image VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (user) REFERENCES User (id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- CREATE TABLE IF NOT EXISTS Comment (
--   id INT NOT NULL AUTO_INCREMENT,
--   user INT NOT NULL,
--   article INT NOT NULL,
--   date DATETIME NOT NULL,
--   content VARCHAR(255) NOT NULL,
--   PRIMARY KEY (id),
--   FOREIGN KEY (user) REFERENCES users (id),
--   FOREIGN KEY (article) REFERENCES articles (id)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;